# Generated by Django 2.0.7 on 2018-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devicename', models.CharField(max_length=32)),
                ('devicesecret', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('if_admin', models.BooleanField()),
            ],
        ),
    ]
