# Generated by Django 2.0.7 on 2018-07-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UandD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('devicename', models.CharField(max_length=32)),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webc.DeviceInfo')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webc.UserInfo')),
            ],
        ),
    ]
